import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#d8f3dc",
    alignItems: "center",
    justifyContent: "center",
  },
  subContainer: {
    shadowColor: "rgba(0,0,0,0.2)",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 5,
    padding: 50,
    borderRadius: 20,
    backgroundColor: "#fff",
  },
  header: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#38b000",
  },
  headerContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  label: {
    fontSize: 19,
    marginRight: 10,
    color: "#004b23",
    fontWeight: "bold",
  },
  input: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: "#004b23",
    borderRadius: 10,
    paddingHorizontal: 10,
    color: "#333",
  },
  dropdown: {
    width: 150,
    height: 40,
    borderWidth: 1,
    borderColor: "#004b23",
    borderRadius: 4,
    paddingHorizontal: 10,
    justifyContent: "center",
    color: "#333",
  },
  dropdownContainer: {
    borderWidth: 1,
    borderColor: "#004b23",
    borderRadius: 5,
    backgroundColor: "#fff",
    paddingVertical: 5,
    paddingHorizontal: 10,
    width: 100,
    maxHeight: 200,
  },
  dropdownText: {
    fontSize: 14,
    color: "#333",
  },
  convertButton: {
    backgroundColor: "#008000",
    borderRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginTop: 20,
    shadowColor: "#004b23",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 5,
  },
  convertButtonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  result: {
    marginTop: 20,
    fontSize: 17,
    color: "#333",
  },

});
